services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: lunettes-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
